# Generated by Django 3.2 on 2023-10-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('color', models.CharField(max_length=7, verbose_name='цвет')),
                ('slug', models.SlugField(max_length=7, unique=True, verbose_name='URL-адрес')),
            ],
        ),
    ]
