# Generated by Django 3.2 on 2023-10-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription_unique_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
    ]
